name: "Conventional Commits"

on:
  # pull_request:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  main:
    name: Validate format
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.GITHUB_HEAD_REF }}
          fetch-tags: true

      - name: Fetch tags
        run: |
          git fetch --tags --quiet
          echo "1 - ${{ github.event.pull_request.head.ref }}"
          echo "2 - ${{ github.event.pull_request.base.ref }}"
          echo "3 - ${{ env.GITHUB_HEAD_REF }}"
          echo "4 - origin/${GITHUB_HEAD_REF}"
          git checkout ${{ github.event.pull_request.head.ref }}

      - name: "Comment"
        uses: marocchino/sticky-pull-request-comment@v2
        # When the previous steps fails, the workflow would stop. By adding this
        # condition you can continue the execution with the populated error message.
        if: always()
        with:
          header: commit-message-lint-error
          message: |
            Hello, world!
            job id: ${{ github.job }}
            echo "README: $(cat README.md)"

      - name: "Label"
        if: always()
        run: |
          echo "GH_REPO=${GH_REPO}"
          echo "NUMBER=${NUMBER}"
          gh issue edit "$NUMBER" --add-label "breaking change"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pull_request.number }}
